# Use an official Node runtime as a parent image
FROM node:14

# Set working directory in Docker container
WORKDIR /app

# Copy package.json and install dependencies
COPY ./app/package.json .
COPY ./app/package-lock.json .
RUN npm install

# Copy the rest of the frontend code
COPY ./app /app

# Start the frontend app
CMD ["npm", "run", "dev"]
