# Use an official Node runtime as a parent image
FROM node:14

# Create app directory
WORKDIR /app/server

# Create a user named "appuser"
RUN useradd -m appuser

# Copy package.json and install dependencies
COPY ./app/server/package.json .
COPY ./app/server/package-lock.json .
RUN npm install

# Copy the rest of the backend code
COPY ./app/server /app/server

# Switch to "appuser"
USER appuser

# Start the backend app
CMD ["npm", "start"]
