# Use an official Node runtime as a parent image
FROM node:14

# Create app directory
WORKDIR /app

# Create a user named "appuser"
RUN useradd -m appuser

# Copy package.json and install dependencies
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install

# Copy the rest of the frontend code
COPY ./ /

# Build the Next.js app for production
RUN npm run build

# Switch to "appuser"
USER appuser

# Start the Next.js app in production mode
CMD ["npm", "start"]