version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: sh -c "npm start"
    ports:
      - "3001:3001"

      